import os
from docx.shared import Inches, Pt, RGBColor
"""
docx_template_filler.py
=======================
Fills a custom .docx template with AI-generated content and engagement metadata.

Responsibilities:
  - Replace {{placeholder}} tokens with engagement metadata
  - Parse AI markdown output into named sections
  - Fill [AI:section_name] markers with AI content
  - Fill [REPEAT] table rows by cloning for each data item
  - Fill structured tables (doc info, version history, campaigns, appendix)

NOT responsible for:
  - Cover page  (generated by generate.js with cover_only=True, merged by app.py)
  - VAJRA branding/styling
  - PDF conversion

Usage:
  from docx_builder.docx_template_filler import fill_docx_template
  success = fill_docx_template(template_path, output_path, meta, ai_text)
"""

import re
import copy
import shutil
import os

from docx import Document
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


# ── Low-level XML helpers ─────────────────────────────────────────────────────

def _clean(text):
    """Strip markdown from text. Never applied to [AI:key] marker names."""
    t = str(text or '')
    if t.strip().startswith('[') and ']' in t:
        return t.strip()
    t = re.sub(r'\*{1,3}([^*]+)\*{1,3}', r'\1', t)
    t = re.sub(r'_{1,2}([^_]+)_{1,2}',   r'\1', t)
    t = re.sub(r'`([^`]+)`',              r'\1', t)
    return t.strip()


def _set_para(p_elem, text):
    """Replace text in a w:p element, preserving first run's formatting."""
    runs = p_elem.findall(qn('w:r'))
    rpr = None
    if runs:
        rp = runs[0].find(qn('w:rPr'))
        if rp is not None:
            rpr = copy.deepcopy(rp)
        for r in list(runs):
            p_elem.remove(r)
    for hl in list(p_elem.findall(qn('w:hyperlink'))):
        p_elem.remove(hl)
    nr = OxmlElement('w:r')
    if rpr is not None:
        nr.append(rpr)
    t = OxmlElement('w:t')
    t.text = _clean(text)
    if t.text and (t.text[0] == ' ' or t.text[-1] == ' '):
        t.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
    nr.append(t)
    p_elem.append(nr)


def _fill_repeat_table(table, data_rows):
    """Replace [REPEAT] template row with actual data rows."""
    tbl_el  = table._tbl
    all_trs = tbl_el.findall(qn('w:tr'))
    if len(all_trs) < 2:
        return
    tmpl_tr = None
    for tr in all_trs[1:]:
        row_text = ''.join(t.text or '' for t in tr.findall('.//' + qn('w:t')))
        if '[REPEAT]' in row_text or not row_text.strip():
            tmpl_tr = tr; break
    if tmpl_tr is None:
        tmpl_tr = all_trs[1]
    for tr in all_trs[1:]:
        tbl_el.remove(tr)
    for row_vals in data_rows:
        new_tr = copy.deepcopy(tmpl_tr)
        tcs    = new_tr.findall(qn('w:tc'))
        for ci, tc in enumerate(tcs):
            if ci >= len(row_vals): break
            for r in list(tc.findall('.//' + qn('w:r'))): r.getparent().remove(r)
            p = tc.find(qn('w:p'))
            if p is None:
                p = OxmlElement('w:p'); tc.append(p)
            nr = OxmlElement('w:r'); t_el = OxmlElement('w:t')
            t_el.text = str(row_vals[ci] or '')
            nr.append(t_el); p.append(nr)
        tbl_el.append(new_tr)


def _extract_date(text, idx=0):
    """Extract the idx-th date from text. Supports MM/DD/YYYY, YYYY-MM-DD etc."""
    dates = re.findall(
        r'\b(?:\d{1,2}[/.\-]\d{1,2}[/.\-]\d{2,4}|\d{4}[/.\-]\d{1,2}[/.\-]\d{1,2})\b', text)
    if not dates: return ''
    return dates[-1] if idx == -1 else (dates[idx] if idx < len(dates) else '')


# ── Placeholder filling ───────────────────────────────────────────────────────

def _fill_placeholders(text, meta):
    """Replace {{token}} with meta values."""
    mapping = {
        'client':          meta.get('client', ''),
        'tester':          meta.get('tester', ''),
        'date':            meta.get('date', ''),
        'engagement_ref':  meta.get('engagement_ref') or meta.get('report_id', ''),
        'classification':  meta.get('classification', 'CONFIDENTIAL'),
        'report_version':  meta.get('report_version', '1.0'),
        'assessment_team': meta.get('assessment_team', meta.get('tester', '')),
        'security_team':   meta.get('assessment_team', meta.get('tester', '')),
        'reviewer':        meta.get('reviewer', ''),
        'approver':        meta.get('approver', ''),
        'target_system':   meta.get('target_system', meta.get('scope', '')),
        'tested_from':     meta.get('tested_from', ''),
        'title':           meta.get('title', ''),
        'scope':           meta.get('scope', ''),
        'prepared_by':            meta.get('tester', ''),
        'classification_short':   (meta.get('classification','CONFIDENTIAL') or 'CONFIDENTIAL').split('\u2014')[0].strip(),
    }
    for k, v in mapping.items():
        text = text.replace('{{' + k + '}}', str(v or ''))
        text = text.replace('{{ ' + k + ' }}', str(v or ''))
    return text


# ── AI section parsing ────────────────────────────────────────────────────────

def parse_ai_sections(ai_text, meta=None):
    """
    Parse AI markdown output into {key: content} dict.
    Derived inline markers (resilience_calc_1, results_stats etc.) are
    synthesised from parsed sections automatically.
    """
    HM = {
        'executive summary':            'executive_summary',
        'results':                      'results_stats',
        'detailed statistics':          'detailed_stats',
        'detailed statistics and':      'detailed_stats',
        'statistics and metrics':       'detailed_stats',
        'overall campaign':             'detailed_stats',
        'individual employee':          'detailed_stats',
        'employee interaction':         'detailed_stats',
        'detailed analysis':            'detailed_analysis',
        'campaign mapped':              'campaign_summary',
        'campaign mapped to':           'campaign_summary',
        'benchmark':                    'benchmark',
        'recommendation':               'recommendation',
        'remediation':                  'remediation',
        'phishing resilience':          'resilience_score',
        'resilience score':             'resilience_score',
        'our calculation':              'our_calculation',
        'interpretation':               'resilience_interpretation',
        'campaign details':             'campaign_details',
        'methodology':                  'methodology',
        'key takeaway':                 'detailed_stats',
        'email pretext':                'email_template_description',
        'observations':                 'detailed_stats',
    }
    for n in range(1, 9):
        HM[f'campaign {n}']            = f'campaign_{n}'
        HM[f'campaign {n}:']           = f'campaign_{n}'
        HM[f'campaign {n} results']    = f'campaign_{n}_stats'
        HM[f'campaign {n} statistics'] = f'campaign_{n}_stats'

    s, ck, cl, in_app = {}, None, [], False

    for line in ai_text.split('\n'):
        st = line.strip()
        is_h = bool(re.match(r'^#{1,4}\s+', st))
        if is_h:
            if ck and cl:
                existing = s.get(ck, '')
                body = '\n'.join(cl).strip()
                s[ck] = (existing + '\n' + body).strip() if existing else body
            ht   = _clean(re.sub(r'^#+\s+', '', st)).lower()
            hlvl = len(st) - len(st.lstrip('#'))
            is_appendix = (hlvl == 1) and 'appendix' in ht
            if is_appendix:
                in_app = True; ck = 'appendix'; cl = []
            elif in_app:
                ck = 'appendix'; cl = [line]   # sub-headings accumulate into appendix
            else:
                in_app = False
                ck = next((v for p, v in HM.items() if p in ht), None)
                if not ck:
                    ck = re.sub(r'[^a-z0-9]', '_', ht)[:25].strip('_') or None
                cl = []
        elif ck:
            cl.append(line)

    if ck and cl:
        existing = s.get(ck, '')
        body = '\n'.join(cl).strip()
        s[ck] = (existing + '\n' + body).strip() if existing else body

    # Derive inline markers
    _derive_meta = meta
    try:
        _derive_markers(s, meta=_derive_meta)
    except Exception as e:
        print(f"[FILLER] Marker derivation warning: {e}")

    return s


def _safe_int(v):
    """Safely convert a value to int, returning 0 on failure."""
    try: return int(str(v).strip().split()[0].replace(',',''))
    except: return 0


def _derive_markers(s, meta=None):
    """Synthesise derived keys (results_stats, resilience_calc_1, etc.)."""
    # Compute resilience score directly from meta numbers if available
    if meta:
        total    = _safe_int(meta.get("total_recipients") or meta.get("emails_sent"))
        clicked  = _safe_int(meta.get("clicked"))
        reported = _safe_int(meta.get("reported"))
        if total and total > 0:
            click_rate   = round(clicked / total * 100, 1) if clicked else 0
            report_rate  = round(reported / total * 100, 1) if reported else 0
            non_click    = round(100 - click_rate, 1)
            resilience   = round((non_click * 0.4) + (report_rate * 0.6), 2)
            s.setdefault("results_stats",
                f"Total: {total} recipients | Phished: {clicked} ({click_rate}%) | "
                f"Reported: {reported} ({report_rate}%) | Resilience Score: {resilience}%")
            s.setdefault("results_metrics",
                f"Click Rate: {click_rate}% | Report Rate: {report_rate}% | "
                f"Non-Click Rate: {non_click}%")
            s.setdefault("resilience_calc_1", f"Non-Click Rate = 100% − {click_rate}% = {non_click}%")
            s.setdefault("resilience_calc_2",
                f"Phishing Resilience Score = [({non_click} × 0.4) + ({report_rate} × 0.6)] = "
                f"{round(non_click*0.4,2)} + {round(report_rate*0.6,2)} = {resilience}")
            s.setdefault("resilience_calc_3", f"Therefore, as percentage: {resilience}%")
    # results_stats
    r = s.get('results', '')
    if r:
        pct = [_clean(l) for l in r.split('\n') if '%' in l and l.strip() and not l.strip().startswith('|')]
        if not pct:
            for l in r.split('\n'):
                if l.strip().startswith('|') and '%' in l and '---' not in l:
                    pts = [_clean(p).strip() for p in l.strip('|').split('|')]
                    if len(pts) >= 2 and '%' in pts[1] and pts[0].lower() not in ('metric', ''):
                        pct.append(f"{pts[0]}: {pts[1]}")
        s.setdefault('results_stats', ' | '.join(pct[:4]) if pct else _clean(r.split('\n')[0])[:200])
        tbl = [l for l in r.split('\n') if l.strip().startswith('|') and '---' not in l]
        ms = [f"{_clean(p[0])}: {_clean(p[1])}"
              for t in tbl[:10]
              for p in [[x.strip() for x in t.strip('|').split('|')]]
              if len(p) >= 2 and p[0] and p[1] and _clean(p[0]).lower() not in ('metric', 'category', '')]
        s.setdefault('results_metrics', ' | '.join(ms[:6]) if ms else s.get('results_stats', '')[:200])

    # recommendation_target — secondary goal/target sentence (distinct from main recommendation)
    rec = s.get('recommendation', '')
    if rec:
        lines_r = [_clean(l) for l in rec.split('\n') if _clean(l) and not _clean(l).startswith('#')]
        # Look for a distinct target/goal sentence
        for ln in lines_r[1:]:  # Skip first line (same as recommendation)
            if any(w in ln.lower() for w in ['71%', 'aim', 'target', 'goal', 'reduce', 'improve', 'achieve']):
                s.setdefault('recommendation_target', ln[:300]); break
        # Fallback: use a generic target if nothing distinct found
        s.setdefault('recommendation_target', 'Aim to achieve a Phishing Resilience Score greater than 71%.')

    # recommendations_text
    src = s.get('remediation', '') or s.get('recommendation', '')
    if src:
        pl = [_clean(l) for l in src.split('\n') if _clean(l) and not _clean(l).startswith('#')]
        s.setdefault('recommendations_text', pl[0][:400] if pl else src[:200])

    # resilience_calc_1/2/3
    calc = (s.get('our_calculation', '') or s.get('resilience_score', '') or
            next((v for v in [s.get('remediation',''), s.get('recommendation','')]
                  if v and ('=' in v or 'non-click' in v.lower() or 'prs' in v.lower())), ''))
    if calc:
        # Skip raw table rows (| col | col |) — they contain % but aren't calc lines
        cl = [_clean(l).lstrip('-*• ')
              for l in calc.split('\n')
              if _clean(l) and not _clean(l).startswith('|')
              and ('=' in l or 'non-click' in l.lower()
                   or 'therefore' in l.lower() or 'prs' in l.lower()
                   or ('rate' in l.lower() and '%' in l and '=' in l))]
        if not cl:
            cl = [_clean(l).lstrip('-*• ') for l in calc.split('\n')
                  if _clean(l) and not _clean(l).startswith('|')]
        if cl:
            s.setdefault('resilience_calc_1', cl[0][:200])
            s.setdefault('resilience_calc_2', cl[min(1, len(cl)-1)][:200])
            s.setdefault('resilience_calc_3', cl[min(2, len(cl)-1)][:200])

    # email_template_description
    for ck in ['campaign_1', 'campaign_details']:
        cs = s.get(ck, '')
        in_template_section = False
        for ln in cs.split('\n'):
            l = _clean(ln).lstrip('-*• ')
            ll = l.lower()
            # Detect "Phishing Email Template:" label — next non-empty line is the description
            if any(x in ll for x in ['phishing email template:', 'email template:']):
                in_template_section = True
                continue
            if in_template_section and l and not l.startswith(('|','#')) and len(l) > 15:
                s.setdefault('email_template_description', l[:300])
                break
            # Also accept lines with pretext/impersonation but NOT starting with 'Campaign'
            if (not in_template_section and len(l) > 20 and not l.startswith(('|','#','Campaign'))
                    and any(w in ll for w in ['pretext','impersonat','subject','template description',
                                              'simulated','lookalike','password expir'])):
                s.setdefault('email_template_description', l[:300]); break
        if 'email_template_description' in s: break
    s.setdefault('email_template_description', 'Phishing email template — see campaign details.')

    # campaign_N_stats — prose only, no raw table rows
    for n in range(1, 9):
        cs = s.get(f'campaign_{n}', '')
        if cs:
            sl = [_clean(l).lstrip('-*• ') for l in cs.split('\n')
                  if _clean(l) and not _clean(l).startswith('|')
                  and any(w in l.lower() for w in
                  ['members','phished','targeted','%','start','end','total','delivered','click'])]
            s.setdefault(f'campaign_{n}_stats', ' | '.join(sl[:3]) if sl else '')

    # detailed_stats — prefer prose lines over raw table markdown
    ds = s.get('detailed_stats', '')
    if ds:
        prose = [_clean(l) for l in ds.split('\n')
                 if _clean(l) and not _clean(l).startswith('|') and not _clean(l).startswith('#')]
        if prose:
            s['detailed_stats'] = prose[0][:400]
        else:
            # Section is all tables — write a brief summary sentence
            s['detailed_stats'] = 'Detailed employee interaction data is presented in the table below.'
        # Override — if it's still a raw table row, replace
        if s.get('detailed_stats','').startswith('|'):
            s['detailed_stats'] = 'Detailed employee interaction data is presented in the table below.'


# ── Campaign & employee extraction ───────────────────────────────────────────

def _extract_campaigns(sections, meta=None):
    """Extract campaign data — prefers structured meta.campaigns over AI text parsing."""

    # Priority 1: Structured campaign data passed directly from the form
    if meta and meta.get("campaigns"):
        campaigns = []
        for i, c in enumerate(meta["campaigns"]):
            if not c: continue
            campaigns.append({
                'num':           i + 1,
                'name':          c.get('title', '') or c.get('topic', '') or f'Campaign {i+1}',
                'topic':         c.get('topic', '') or c.get('title', '') or f'Campaign {i+1}',
                'group':         c.get('group', ''),
                'total_members': str(c.get('total', '') or ''),
                'phished':       str(c.get('phished', '') or '0'),
                'start_date':    c.get('start', '') or '',
                'end_date':      c.get('end', '') or '',
                'pretext':       c.get('pretext', '') or '',
                '_raw':          '',
            })
        if campaigns:
            print(f"[FILLER] Using {len(campaigns)} structured campaigns from form data")
            return campaigns

    campaigns = []

    # First priority: campaign_summary TABLE rows from AI output
    # These have the most complete data for all campaigns
    summary_text = sections.get('campaign_summary', '')
    for line in summary_text.split('\n'):
        if line.strip().startswith('|') and '---' not in line:
            pts = [_clean(p).strip() for p in line.strip('|').split('|')]
            if len(pts) >= 4 and pts[0] and re.match(r'^\d+$', pts[0]):
                campaigns.append({
                    'num':           int(pts[0]),
                    'name':          pts[1],
                    'topic':         pts[1],
                    'group':         pts[2],
                    'total_members': pts[3].replace(' members', ''),
                    'phished':       pts[4] if len(pts) > 4 else '0',
                    'start_date':    '', 'end_date':    '', '_raw': '',
                })

    # Enrich with details from campaign_N sections (start/end dates, better title)
    for c in campaigns:
        cs = sections.get(f"campaign_{c['num']}", '')
        if not cs: continue
        c['_raw'] = cs
        for line in cs.split('\n'):
            l = re.sub(r'\*+', '', _clean(line)).lstrip('-• ').strip()
            ll = l.lower()
            for fld, pats in [
                ('start_date', ['start date:', 'start:', 'launched:','campaign start:']),
                ('end_date',   ['end date:', 'end:', 'closed:','campaign end:']),
                ('topic',      ['campaign name:', 'campaign theme:', 'pretext:','email pretext:']),
                ('group',      ['group targeted:','target group:','department:']),
            ]:
                for pat in pats:
                    if ll.startswith(pat) and not c.get(fld):
                        c[fld] = l[len(pat):].strip()[:80]; break
        if not c['start_date']: c['start_date'] = _extract_date(cs, 0)
        if not c['end_date']:   c['end_date']   = _extract_date(cs, -1)

    if campaigns:
        return campaigns

    # Fallback: extract from campaign_N sections directly
    for n in range(1, 9):
        cs = sections.get(f'campaign_{n}', '')
        if not cs: continue
        cd = {'num':n,'name':f'Campaign {n}','topic':'','group':'',
              'total_members':'','phished':'0','start_date':'','end_date':'','_raw':cs}
        for line in cs.split('\n'):
            # Handle both plain "Key: val" and bold "**Key:** val" markdown
            l = re.sub(r'\*+', '', _clean(line)).lstrip('-• ').strip()
            ll = l.lower()
            for fld, pats in [
                ('topic',         ['campaign name:','campaign theme:','pretext:','email pretext:','name:','subject line:']),
                ('group',         ['group targeted:','target group:','target population:','department:','targeted group:']),
                ('total_members', ['total targeted:','total members:','total employees:','total recipients:']),
                ('phished',       ['phished:','failed:','credentials submitted:','clicked:','link clicked:']),
                ('start_date',    ['start date:','start:','launched:','campaign start:']),
                ('end_date',      ['end date:','end:','closed:','campaign end:']),
            ]:
                for pat in pats:
                    if ll.startswith(pat):
                        val = l[len(pat):].strip()
                        # Extract just the number/value before any % or extra text
                        if fld in ('total_members','phished'):
                            m = re.match(r'^(\d+)', val)
                            if m: val = m.group(0)
                        cd[fld] = val[:80]; break
        if not cd['topic']:
            for line in cs.split('\n'):
                l = _clean(line).lstrip('-*# ')
                if re.match(r'^Campaign \d+:?\s*$', l, re.I): continue
                if l and len(l) > 5 and not l.startswith(('|','#')): cd['topic'] = l[:80]; break
        if not cd['start_date']: cd['start_date'] = _extract_date(cs, 0)
        if not cd['end_date']:   cd['end_date']   = _extract_date(cs, -1)
        campaigns.append(cd)

    if not campaigns:
        for line in sections.get('campaign_summary', '').split('\n'):
            if line.strip().startswith('|') and '---' not in line:
                pts = [_clean(p).strip() for p in line.strip('|').split('|')]
                if len(pts) >= 4 and pts[0] and re.match(r'^\d+$', pts[0]):
                    campaigns.append({'num':int(pts[0]),'name':pts[1],'topic':pts[1],
                                      'group':pts[2],'total_members':pts[3].replace(' members',''),
                                      'phished':pts[4] if len(pts)>4 else '0',
                                      'start_date':'','end_date':'','_raw':''})

    # For campaigns with no group, try to get from campaign_N section
    for c in campaigns:
        if not c.get('group'):
            cs = sections.get(f"campaign_{c['num']}", '')
            for line in cs.split('\n'):
                l = _clean(line).lstrip('-*• '); ll = l.lower()
                for pat in ['group targeted:','target group:','target population:','department:']:
                    if ll.startswith(pat):
                        c['group'] = l[len(pat):].strip()[:80]; break
                if c.get('group'): break

    return campaigns


def _extract_employees(sections):
    employees = []; seen = set()
    for key in ['appendix', 'detailed_stats', 'detailed_analysis']:
        for line in sections.get(key, '').split('\n'):
            if not line.strip().startswith('|') or '---' in line: continue
            pts = [_clean(p).strip() for p in line.strip('|').split('|')]
            if not pts: continue
            if pts[0].lower() in ('employee id','#','no','') or 'name' in pts[0].lower(): continue
            if not (re.match(r'^EMP-', pts[0], re.I) or re.match(r'^\d+$', pts[0])): continue
            if pts[0] in seen: continue
            seen.add(pts[0])

            # Find email column — search ALL columns for @
            email_col = next((i for i, p in enumerate(pts) if '@' in p), -1)
            email = pts[email_col] if email_col >= 0 else ''

            # Detect layout: EMP-ID | Name | Dept | Email | Opened | Clicked | Creds | Time | Outcome
            if email_col == 3 and len(pts) >= 4:
                employees.append({
                    'id':pts[0], 'name':pts[1], 'dept':pts[2], 'email':pts[3],
                    'opened':pts[4] if len(pts)>4 else '', 'clicked':pts[5] if len(pts)>5 else '',
                    'creds':pts[6] if len(pts)>6 else '', 'time':pts[7] if len(pts)>7 else '',
                    'outcome':pts[8] if len(pts)>8 else '', '_all':pts})
            elif email_col == 1 and len(pts) >= 3:
                # # | Email | Dept
                employees.append({'id':pts[0],'name':'','dept':pts[2] if len(pts)>2 else '',
                                   'email':pts[1],'opened':'','clicked':'','creds':'',
                                   'time':'','outcome':'','_all':pts})
            else:
                # Flexible mapping: try to identify columns by content
                # Common AI output: EMP-ID | Name | Dept | Email | Opened | Clicked | Creds | Time | Outcome
                # or shorter:       EMP-ID | Name | Dept | Email | Time | Outcome
                opened  = next((p for p in pts[4:] if p.lower() in ('yes','no')), '')
                clicked = next((p for i,p in enumerate(pts[4:]) if p.lower() in ('yes','no') and i > 0), '')
                creds   = next((p for i,p in enumerate(pts[4:]) if p.lower() in ('yes','no') and i > 1), '')
                time_v  = next((p for p in pts if 'min' in p.lower() or 'n/a' in p.lower()), '')
                outcome = next((p for p in reversed(pts) if any(w in p.lower()
                               for w in ['failed','clicked only','passed','no interaction'])), pts[-1] if pts else '')
                employees.append({'id':pts[0], 'name':pts[1] if len(pts)>1 else '',
                                   'dept':pts[2] if len(pts)>2 else '',
                                   'email':email, 'opened':opened, 'clicked':clicked,
                                   'creds':creds, 'time':time_v, 'outcome':outcome, '_all':pts})
    return employees


# ── Table fillers ─────────────────────────────────────────────────────────────

def _run_plain(para, text, color="000000", size=11, italic=False):
    run = para.add_run(text)
    run.font.size = Pt(size)
    run.font.italic = italic
    h = color.lstrip('#')
    run.font.color.rgb = RGBColor(int(h[0:2],16), int(h[2:4],16), int(h[4:6],16))


def _safe_logo_path(logo_path):
    """Convert any image to a temporary PNG so add_picture always works."""
    if not logo_path:
        print("[FILLER] Logo: no path provided")
        return None
    if not os.path.exists(logo_path):
        print(f"[FILLER] Logo: file not found at: {logo_path}")
        return None
    print(f"[FILLER] Logo: found {os.path.getsize(logo_path)} bytes at {logo_path}")
    try:
        from PIL import Image
        import tempfile
        img = Image.open(logo_path).convert("RGBA")
        # Composite onto white background (handles transparency)
        bg = Image.new("RGB", img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[3] if img.mode == "RGBA" else None)
        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        bg.save(tmp.name, "PNG")
        tmp.close()
        return tmp.name
    except ImportError:
        return logo_path  # PIL not available — try original path directly
    except Exception as e:
        print(f"[FILLER] Logo convert warning: {e}")
        return logo_path  # fallback to original


def _fill_logo_placeholders(doc, meta):
    """Replace cover logo placeholders with uploaded logos or hint text."""
    comp_logo = meta.get("_company_logo")
    test_logo = meta.get("_tester_logo")
    _tmp_files = []

    for para in doc.paragraphs:
        txt = para.text.strip()

        if "{{company_logo_placeholder}}" in txt:
            for run in list(para.runs):
                run._element.getparent().remove(run._element)
            para.paragraph_format.alignment = 1
            safe_path = _safe_logo_path(comp_logo)
            if safe_path:
                if safe_path != comp_logo:
                    _tmp_files.append(safe_path)
                try:
                    para.add_run().add_picture(safe_path, width=Inches(3.5))
                    print(f"[FILLER] ✓ Company logo placed on cover ({safe_path})")
                except Exception as e:
                    print(f"[FILLER] Company logo error: {type(e).__name__}: {e}")
                    # Try raw path as last resort
                    try:
                        para.add_run().add_picture(comp_logo, width=Inches(3.5))
                        print(f"[FILLER] ✓ Company logo placed (raw path fallback)")
                    except Exception as e2:
                        print(f"[FILLER] Company logo final error: {e2}")
                        _run_plain(para, "[ Client Logo ]", color="1C3F6E", size=14)
            else:
                _run_plain(para, "[ Client Logo — upload via Logos tab ]", color="6B8CAE", size=11, italic=True)

        elif "{{tester_logo_placeholder}}" in txt:
            for run in list(para.runs):
                run._element.getparent().remove(run._element)
            para.paragraph_format.alignment = 1
            safe_path = _safe_logo_path(test_logo)
            if safe_path:
                if safe_path != test_logo:
                    _tmp_files.append(safe_path)
                try:
                    para.add_run().add_picture(safe_path, width=Inches(2.0))
                    print(f"[FILLER] ✓ Assessor logo placed on cover ({safe_path})")
                except Exception as e:
                    print(f"[FILLER] Assessor logo error: {type(e).__name__}: {e}")
                    try:
                        para.add_run().add_picture(test_logo, width=Inches(2.0))
                        print(f"[FILLER] ✓ Assessor logo placed (raw path fallback)")
                    except Exception as e2:
                        print(f"[FILLER] Assessor logo final error: {e2}")
                        _run_plain(para, "[ Assessor Logo ]", color="6B8CAE", size=11)
            else:
                _run_plain(para, "[ Assessor Logo — upload via Logos tab ]", color="6B8CAE", size=11, italic=True)

    # Clean up temp PNG files
    for tmp in _tmp_files:
        try: os.unlink(tmp)
        except: pass


def _fill_doc_info(doc, meta):
    LABELS = {'document title','version number','date of issue','status',
              'classification','performed by','author','reviewer','approver',
              'department','document type'}
    VM = {'document title': f"Phishing Simulation Report \u2014 {meta.get('client','')}",
          'version number': meta.get('report_version','1.0'),
          'date of issue':  meta.get('date',''),
          'status':         'Draft',
          'classification': meta.get('classification','CONFIDENTIAL'),
          'performed by':   meta.get('tester',''),
          'author':         meta.get('author', meta.get('tester','')),
          'reviewer':       meta.get('reviewer',''),
          'approver':       meta.get('approver',''),
          'department':     meta.get('assessment_team',''),
          'document type':  'Technical Report'}
    for tbl in doc.tables:
        if not tbl.rows or len(tbl.rows[0].cells) != 2: continue
        if tbl.rows[0].cells[0].text.strip().lower() not in LABELS: continue
        for row in tbl.rows:
            if len(row.cells) < 2: continue
            lbl = row.cells[0].text.strip().lower()
            for k, v in VM.items():
                if k in lbl and v:
                    ps = row.cells[1]._tc.findall(qn('w:p'))
                    if ps: _set_para(ps[0], v); break


def _fill_version_history(doc, meta):
    for tbl in doc.tables:
        hdr = [c.text.strip() for c in tbl.rows[0].cells] if tbl.rows else []
        if 'Version' in hdr and 'Author' in hdr and len(tbl.rows) > 1:
            cells = tbl.rows[1].cells
            for ci, v in enumerate([meta.get('report_version','1.0'), meta.get('date',''),
                                     meta.get('tester',''), 'Final report issued']):
                if ci < len(cells):
                    ps = cells[ci]._tc.findall(qn('w:p'))
                    if ps and v: _set_para(ps[0], v)
            break


def _fill_distribution_list(doc, meta):
    for tbl in doc.tables:
        hdr = [c.text.strip() for c in tbl.rows[0].cells] if tbl.rows else []
        if 'Name' in hdr and 'Title' in hdr and 'Department' in hdr:
            rows = []
            dist_raw = meta.get('distribution_list', '')
            if dist_raw:
                for line in dist_raw.strip().split('\n'):
                    line = line.strip()
                    if not line: continue
                    parts = [p.strip() for p in line.split('|')]
                    while len(parts) < 4: parts.append('')
                    parts[3] = parts[3] or meta.get('date', '')
                    rows.append(parts[:4])
            # Always include the tester at top
            rows.insert(0, [meta.get('tester',''), 'Lead Assessor',
                            meta.get('assessment_team',''), meta.get('date','')])
            _fill_repeat_table(tbl, rows)
            print(f"[FILLER] Distribution list: {len(rows)} entries")
            break


def _fill_recommendations_table(doc, meta, sections):
    for tbl in doc.tables:
        hdr = [c.text.strip() for c in tbl.rows[0].cells] if tbl.rows else []
        if 'Responsible Team' in hdr and len(tbl.rows) > 1:
            cells = tbl.rows[1].cells
            if cells:
                ps = cells[0]._tc.findall(qn('w:p'))
                if ps: _set_para(ps[0], meta.get('assessment_team',''))
            if len(cells) > 1:
                rec = _clean(sections.get('recommendations_text',''))
                ps  = cells[1]._tc.findall(qn('w:p'))
                if ps and rec: _set_para(ps[0], rec[:400])
            break


def _fill_campaign_summary_table(doc, campaigns):
    for tbl in doc.tables:
        hdr = [c.text.strip() for c in tbl.rows[0].cells] if tbl.rows else []
        if '#' in hdr and any('Campaign' in c for c in hdr) and 'Phished' in hdr and campaigns:
            _fill_repeat_table(tbl, [
                [str(c['num']), _clean(c.get('name',c.get('topic',''))), _clean(c.get('group','')),
                 (c.get('total_members','') or '—') + ' members', str(c.get('phished','0'))]
                for c in campaigns])
            break


def _fill_campaign_detail_tables(doc, campaigns):
    camp_idx = 0
    for tbl in doc.tables:
        hdr_str = ' '.join(c.text.strip() for c in tbl.rows[0].cells).lower() if tbl.rows else ''
        if 'campaign topic' not in hdr_str: continue
        if camp_idx >= len(campaigns):
            # No data for this campaign slot — clear placeholder VALUES, keep LABEL cells
            LABEL_CELLS = {'campaign topic', 'campaign title', 'group targeted',
                           'total members & phished', 'start date', 'end date'}
            for row in tbl.rows:
                for cell in row.cells:
                    ct = cell.text.strip()
                    ct_lower = ct.lower()
                    # Only clear cells that are placeholder values, not structural labels
                    is_label = ct_lower in LABEL_CELLS
                    is_placeholder = (ct.startswith('[') or ct == '[DD/MM/YYYY]'
                                      or (ct.startswith('Campaign ') and not is_label))
                    if is_placeholder and not is_label:
                        ps = cell._tc.findall(qn('w:p'))
                        if ps: _set_para(ps[0], '')
            camp_idx += 1
            continue
        c = campaigns[camp_idx] if camp_idx < len(campaigns) else {}
        camp_idx += 1
        vm = {
            'campaign topic':         _clean(c.get('topic', c.get('name', f'Campaign {camp_idx}'))),
            'group targeted':         _clean(c.get('group', '')),
            'campaign title':         _clean(c.get('name', c.get('topic', f'Campaign {camp_idx}')))[:40],
            'total members & phished': f"{c.get('total_members','—') or '—'} Members / {c.get('phished','0')} Phished",
            'start date':             (_clean(c.get('start_date','')) or _extract_date(c.get('_raw',''), 0)).split('|')[0].strip(),
            'end date':               _clean(c.get('end_date',''))   or _extract_date(c.get('_raw',''), -1),
        }
        for row in tbl.rows:
            for ci in range(0, len(row.cells)-1, 2):
                lbl = row.cells[ci].text.strip().lower()
                for k, v in vm.items():
                    if k in lbl and v:
                        ps = row.cells[ci+1]._tc.findall(qn('w:p'))
                        if ps: _set_para(ps[0], v); break


def _fill_employee_9col(doc, employees):
    """Fill employee interaction table, aligning columns by header names."""
    FIELD_MAP = {
        'employee id':            'id',
        'id':                     'id',
        'name':                   'name',
        'department':             'dept',
        'email':                  'email',
        'email address':          'email',
        'opened':                 'opened',
        'email opened':           'opened',
        'clicked':                'clicked',
        'link clicked':           'clicked',
        'credentials':            'creds',
        'credentials submitted':  'creds',
        'time':                   'time',
        'time to click':          'time',
        'outcome':                'outcome',
    }
    for tbl in doc.tables:
        hdr     = [c.text.strip() for c in tbl.rows[0].cells] if tbl.rows else []
        hdr_str = ' '.join(hdr).lower()
        if 'employee id' not in hdr_str and 'emp-' not in hdr_str: continue
        if 'opened' not in hdr_str and 'clicked' not in hdr_str: continue

        # Map header columns to field names
        col_fields = []
        for h in hdr:
            hl = h.lower().strip()
            field = next((v for k, v in FIELD_MAP.items() if k in hl), None)
            col_fields.append(field)

        rows = []
        for emp in employees:
            row = []
            for field in col_fields:
                if field:
                    row.append(emp.get(field, '—') or '—')
                else:
                    row.append('—')
            rows.append(row)

        if rows:
            _fill_repeat_table(tbl, rows)
            print(f"[FILLER] Filled 9-col employee table: {len(rows)} rows")
        break


def _fill_appendix_table(doc, employees, meta=None):
    """Fill appendix employee table — prefers structured meta.phished_employees."""
    # Try structured data from form first
    structured = []
    phished_raw = (meta or {}).get('phished_employees', '')
    if phished_raw:
        for i, line in enumerate(phished_raw.strip().split('\n')):
            line = line.strip()
            if not line: continue
            if ' | ' in line:
                parts = [p.strip() for p in line.split(' | ')]
            else:
                parts = [line, '']
            email = parts[0] if parts else ''
            dept  = parts[1] if len(parts) > 1 else ''
            if email:
                structured.append({'email': email, 'dept': dept})
        if structured:
            employees = structured

    for tbl in doc.tables:
        hdr = [c.text.strip() for c in tbl.rows[0].cells] if tbl.rows else []
        if '#' in hdr and 'Email' in hdr and 'Department' in hdr and employees:
            _fill_repeat_table(tbl, [[str(i+1), e['email'], e['dept']] for i, e in enumerate(employees)])
            print(f"[FILLER] Filled appendix table: {len(employees)} employees")
            break


def _fill_all_placeholders(doc, meta):
    # Fill body paragraphs
    for para in doc.paragraphs:
        if '{{' in para.text:
            _set_para(para._p, _fill_placeholders(para.text, meta))
    # Fill table cells
    for tbl in doc.tables:
        for row in tbl.rows:
            for cell in row.cells:
                for para in cell.paragraphs:
                    if '{{' in para.text:
                        _set_para(para._p, _fill_placeholders(para.text, meta))
    # Fill headers and footers — {{classification_short}}, {{report_version}}, etc.
    for section in doc.sections:
        for hdr_ftr in [section.header, section.footer,
                        section.first_page_header, section.first_page_footer,
                        section.even_page_header, section.even_page_footer]:
            if hdr_ftr is None:
                continue
            try:
                for para in hdr_ftr.paragraphs:
                    if '{{' in para.text:
                        _set_para(para._p, _fill_placeholders(para.text, meta))
                for tbl in hdr_ftr.tables:
                    for row in tbl.rows:
                        for cell in row.cells:
                            for para in cell.paragraphs:
                                if '{{' in para.text:
                                    _set_para(para._p, _fill_placeholders(para.text, meta))
            except Exception:
                pass


def _fill_ai_markers(doc, sections):
    MARKER    = re.compile(r'^\[AI:([\w]+)\]$')
    BARE      = re.compile(r'^\[([\w]+)\]$')
    INLINE    = re.compile(r'\[AI:([\w]+)\]')
    for para in doc.paragraphs:
        raw = para.text.strip()
        m   = MARKER.match(raw) or BARE.match(raw)
        if m:
            key = m.group(1).lower()
            val = sections.get(key, '')
            if val:
                _set_para(para._p, _clean(val).split('\n')[0].strip()[:500])
                print(f"[FILLER] Filled: [{key}]")
            else:
                _set_para(para._p, '')  # clear unfilled markers — no visible [key] in output
        elif '[AI:' in raw:
            mi = INLINE.search(raw)
            if mi:
                key = mi.group(1).lower()
                val = sections.get(key, '')
                if val:
                    _set_para(para._p, raw.replace(mi.group(0), _clean(val).split('\n')[0].strip()[:200]))
    for tbl in doc.tables:
        for row in tbl.rows:
            for cell in row.cells:
                for para in cell.paragraphs:
                    raw = para.text.strip()
                    if '[AI:' in raw:
                        mi = INLINE.search(raw)
                        if mi:
                            key = mi.group(1).lower()
                            val = sections.get(key, '')
                            if val:
                                _set_para(para._p, _clean(val).split('\n')[0].strip()[:400])


# ── Main entry point ──────────────────────────────────────────────────────────

def _fill_header_footer_xml(output_path, meta):
    """
    Fill {{placeholders}} in header/footer XML files directly.
    Required because headers/footers often contain text boxes (wps:txbx)
    that python-docx's section.header/footer API cannot access.
    """
    import zipfile, shutil, tempfile

    mapping = {
        '{{classification_short}}': (meta.get('classification','CONFIDENTIAL') or 'CONFIDENTIAL').split('—')[0].strip(),
        '{{report_version}}':       meta.get('report_version', '1.0') or '1.0',
        '{{client}}':               meta.get('client', '') or '',
        '{{tester}}':               meta.get('tester', '') or '',
        '{{date}}':                 meta.get('date', '') or '',
        '{{assessment_team}}':      meta.get('assessment_team', '') or '',
        '{{classification}}':       meta.get('classification', 'CONFIDENTIAL') or 'CONFIDENTIAL',
    }

    # Read zip, edit, write back
    tmp = output_path + '.hdrtmp'
    try:
        with zipfile.ZipFile(output_path, 'r') as zin:
            file_data = {n: zin.read(n) for n in zin.namelist()}

        changed = False
        for name in list(file_data.keys()):
            if not (name.startswith('word/header') or name.startswith('word/footer')):
                continue
            if not name.endswith('.xml'):
                continue
            xml = file_data[name].decode('utf-8')
            original = xml
            for placeholder, value in mapping.items():
                xml = xml.replace(placeholder, str(value))
            if xml != original:
                file_data[name] = xml.encode('utf-8')
                changed = True
                print(f"[FILLER] Filled header/footer placeholders in {name}")

        if changed:
            with zipfile.ZipFile(tmp, 'w', zipfile.ZIP_DEFLATED) as zout:
                for name, data in file_data.items():
                    zout.writestr(name, data)
            shutil.move(tmp, output_path)
    except Exception as e:
        print(f"[FILLER] Header/footer XML fill warning: {e}")
        if os.path.exists(tmp):
            os.unlink(tmp)


def fill_docx_template(template_path, output_path, meta, ai_content_text):
    """
    Fill a .docx template with engagement metadata and AI content.
    Cover page is NOT added here — app.py merges the VAJRA cover separately.

    Returns True on success, False on failure.
    """
    try:
        print(f"[FILLER] Loading template: {template_path}")
        shutil.copy2(template_path, output_path)
        doc = Document(output_path)

        # 1. Parse AI sections
        sections = parse_ai_sections(ai_content_text, meta=meta)
        print(f"[FILLER] Sections: {[k for k in sections if not k.startswith('_')][:14]}")

        # 2. Fill logos first — must see raw {{logo_placeholder}} before _fill_all_placeholders wipes them
        _fill_logo_placeholders(doc, meta)

        # 3. Fill {{placeholders}}
        _fill_all_placeholders(doc, meta)

        # 4. Fill [AI:marker] paragraphs and table cells
        _fill_ai_markers(doc, sections)

        # 5. Fill structured metadata tables
        _fill_doc_info(doc, meta)
        _fill_version_history(doc, meta)
        _fill_distribution_list(doc, meta)
        _fill_recommendations_table(doc, meta, sections)

        # 5. Fill campaign tables
        campaigns = _extract_campaigns(sections, meta=meta)
        print(f"[FILLER] Campaigns: {len(campaigns)}")
        _fill_campaign_summary_table(doc, campaigns)
        _fill_campaign_detail_tables(doc, campaigns)

        # 6. Fill employee tables
        employees = _extract_employees(sections)
        print(f"[FILLER] Employees: {len(employees)}")
        _fill_employee_9col(doc, employees)
        _fill_appendix_table(doc, employees, meta=meta)

        doc.save(output_path)
        # Fill header/footer text boxes that python-docx API can't reach
        _fill_header_footer_xml(output_path, meta)
        print(f"[FILLER] Saved: {output_path} ({os.path.getsize(output_path):,} bytes)")

        # NOTE: No VAJRA cover prepended for .docx templates.
        # The custom .docx template already contains its own cover page
        # with {{placeholders}} filled above. Adding another cover would duplicate it.
        # VAJRA cover is only used for .md template outputs (generate.js path).
        print("[FILLER] ✓ Custom .docx template filled — using template's own cover page")
        return True

    except Exception as e:
        import traceback
        print(f"[FILLER] Error: {e}")
        traceback.print_exc()
        return False
